name: Feature Request
description: Suggest an idea for this project
title: "[Feat]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve!

  - type: textarea
    id: issue
    attributes:
      label: "Describe the problem and solution that you'd like."
      description: A clear description of what you want to happen.
      placeholder: "Example: When clicking this I want that."

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives that you have considered."
      description: "A clear description of any alternative solutions or features you've considered."
      placeholder: "Example: Instead of this it should do that."

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information or resources related to this feature request.
      placeholder: "e.g., links to resources, screenshots, etc."

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Please list the criteria that will determine when this feature is considered complete.
      placeholder: "List the acceptance criteria..."
