name: Build and deploy Node.js app to Azure Web App - web-app-prod

on:
  push:
    branches:
      - web-app
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          cd commanddash_web_app
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Zip artifact for deployment
        run: |
          cd commanddash_web_app/build
          zip -r ../release.zip build node_modules package.json package-lock.json
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: sveltekit-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: sveltekit-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_818727A488FB487EA3BCC61BEC337FDD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_58CC6F3841FB49A38469650AD296DCC8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7B7BF9D41759471DBA0ED64C44AF88AE }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "web-app-prod"
          slot-name: "Production"
          package: deploy
